# Generated by Django 5.1 on 2024-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_set',
            fields=[
                ('full_name', models.CharField(max_length=150)),
                ('ph_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('profession', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
